 - name: copy ssh_config file to targets
   copy:
     src: sshd_config
     dest: sshdconfig
     owner: root
     group: root
     mode: 0600
- name: this task to restart service
   service: sshd
   status: restarted
   